config/routes.rb
Rails.application.routes.draw do
    get 'profile/index'
    patch 'profile/savechanges'
    get 'data/search'
    get 'data/show'
    get 'data/myoffers'
    get 'data/report'
    get 'data/edit'
    get 'data/index'
    get 'data/savechanges'
    patch 'data/savechanges'
    get 'data/add'
    get 'data/create'
    get 'search/index'
    get 'search/org_search'
    get 'search/data_search'
    get 'search/to_search'
    get 'otchet/index'
    get 'search/report'

    post 'data/create', to: 'data#create' 
    get 'mains/show'

  resources :mains
  resources :otchet
    devise_for :users, :controllers => { :registrations => "users/registrations"}
as :user do
    get "users/sign_up", to: "registrations#new", as: "new"
  end
    root 'mains#index'

end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	belongs_to :user

	def self.to_csv(options = {})
    	CSV.generate(options) do |csv|
      		csv << column_names
     		all.each do |offer|
       		 csv << offer.attributes.values_at(*column_names)
      		end
    	end
	end
	validates_presence_of :obcode
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
end

app/models/otdel.rb
class Otdel < ActiveRecord::Base
	has_many :offers
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :offers, foreign_key: "user_id"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
class DataController < ApplicationController
	before_filter :authenticate_user!
	def add
		@user = current_user
		@offer = @user.offers.new
	end

	def myoffers 
		@BiD=[]
		Offer.where(user_id: current_user.id).each do |f|
			@BiD.push(f)
		end
	end

	def index
		@user = current_user
		@offer = @user.offers.new

	end

	def show
		@user = current_user
		@offer = @user.offers.new

	end
	
	def create 
		#занесение нарушения в БД offers
		@user = current_user
		@offer = @user.offers.new
		@offer.obcode = params[:offer][:obcode]
		@offer.reason = params[:offer][:reason]
		@offer.adress = params[:offer][:adress]
		@offer.offertype = params[:offer][:offertype]
		@torg = Organisation.find_or_create_by(name: params[:offer][:org])
		@offer.organisation_id = @torg.id
		@offer.offerstat = params[:offer][:offerstat]
		@offer.kolpredp = params[:offer][:kolpredp]
		@offer.kolpredupr = params[:offer][:kolpredupr]
		@offer.kolshtraf = params[:offer][:kolshtraf]
		@offer.summshtraf = params[:offer][:summshtraf]
		@tto = Otdel.find_or_create_by(name: params[:offer][:to])
		@offer.otdel_id = @tto.id
		@offer.save
		# respond_to do |format|
  # if @offer.save
  #   format.js { render :js=>'alert("Заявка добавлена");' }
  # else
  #   format.js { render :js=>'alert("Заполните все поля");' }
  # end
# end  

	end

	def edit
		@offer = Offer.find(params[:f])

	end


	def savechanges
		@user = current_user
		@offer = Offer.find(params[:offer][:id])
		@offer.update_attribute(:obcode,params[:offer][:obcode])
		@offer.update_attribute(:reason,params[:offer][:reason])
		@offer.update_attribute(:adress,params[:offer][:adress])
		@offer.update_attribute(:offertype,params[:offer][:offertype])
		@offer.update_attribute(:offerstat,params[:offer][:offerstat])
		@offer.update_attribute(:kolpredp,params[:offer][:kolpredp])
		@offer.update_attribute(:kolpredupr,params[:offer][:kolpredupr])
		@offer.update_attribute(:kolshtraf,params[:offer][:kolshtraf])
		@offer.update_attribute(:summshtraf,params[:offer][:summshtraf])
		@offer.save
		redirect_to "/data/myoffers"
	end
	

end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_filter :authenticate_user!
  before_action only: [:show, :edit, :update, :destroy]

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: 'Main was successfully created.' }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/controllers/otchet_controller.rb
class OtchetController < ApplicationController
	  def index
    @offer = Offer.all
    respond_to do |format|
      format.html
      format.csv { send_data @offer.to_csv }
      format.xls #{ send_data @offer.to_csv(col_sep: "\t") }
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	before_filter :authenticate_user!

	def index
		@user = current_user
	end
	def savechanges
		@user = current_user
		@user.update_attribute(:fname, params[:user][:fname])
		@user.update_attribute(:lname, params[:user][:lname])
		@user.update_attribute(:oname, params[:user][:oname])
		@user.update_attribute(:to, params[:user][:to])
		@user.update_attribute(:access, params[:user][:access])
		@user.update_attribute(:email, params[:user][:email])
		redirect_to "/mains/"
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_filter :authenticate_user!
	before_filter :can_search, only: [:index]

  def index
	@SDB=[]
	if params[:requesti]=="data" 
	date1 = DateTime.new(params[:start_date]["year"].to_i, params[:start_date]["month"].to_i, params[:start_date]["day"].to_i)
	date2 = DateTime.new(params[:end_date]["year"].to_i, params[:end_date]["month"].to_i, params[:end_date]["day"].to_i)
	Offer.where(created_at: [date1..date2]).each do |f|
		@SDB.push(f)
	end



	elsif params[:requesti]=="otdel"
			Offer.where(otdel_id: params[:to]).each do |f|
				@SDB.push(f)
			end


	elsif params[:requesti]=="org"
		Offer.where(organisation_id: params[:organisation_id]).each do |f|
			@SDB.push(f)
		end
	end

    respond_to do |format|
      format.html
      format.csv { send_data @SDB.to_csv }
      format.xls
    end
  end
    def can_search
    	@user= current_user
    if @user.access=="1"
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :update_sanitized_params, if: :devise_controller?
  skip_before_filter :require_no_authentication, only: [:new, :create]

    def update_sanitized_params
       devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email,   :password, :password_confirmation,
          :fname, :lname, :oname, :access, :to)}
    end

  def new
    super
  end

  def create
  	super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/otchet_helper.rb
module OtchetHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/search_helper.rb
module SearchHelper

end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/create.html.erb
<p id="notice"><%= notice %></p>

app/views/data/edit.html.erb
<script>
$(document).on("page:change", function() {
  $("#form-group").submit(function() {
    $.ajax({
      type: 'POST',
      dataType: 'html',
      url: $(this).attr("action"),
      data:   $(this).serialize() 
      success: function() {
        alert("Done");
      }
    });
  });
});
</script>
<h1>Нарушение #  <%= @offer.id%> </h1>
<%= form_for @offer, url: {action: "savechanges"}, html: {class: "form-group"} do |f| %>
<div class="form-group">
  ID </br>
  <%= f.text_field :id %>
</div>
<div class="form-group">
  Код объекта</br>
  <%= f.text_field :obcode, :required=>true%>
</div>
<div class="form-group">
 Причина</br>
 <%= f.text_area :reason, size: "60x12", :required=>true %>
</div>
<div class="form-group">
 Адрес </br>
   <%= f.text_field :adress, :required=>true %>
</div>
<div class="form-group">
 Тип нарушения </br>
   <%= f.text_field :offertype, :required=>true %>
</div>
<div class="form-group">
 Id организации  </br>
  <%= f.text_field :organisation_id, :required=>true %>
</div>
<div class="form-group">
 Статья наурушения </br>
   <%= f.text_field :offerstat, :required=>true %>
</div>
<div class="form-group">
 Количество предписаний  </br>
  <%= f.text_field :kolpredp, :required=>true%>
</div>
<div class="form-group">
 Количество штрафов  </br>
  <%= f.text_field :kolshtraf , :required=>true%>
</div>
<div class="form-group">
  Сумма штрафов</br>
    <%= f.text_field :summshtraf, :required=>true %>
</div>
  <%= f.submit "Create" %>
<% end %>

app/views/data/index.html.erb
<script>

	$(document).ready(function() {
		$("#popup").magnificPopup();

		$("#nifty_form").submit(function() {
			$.ajax({
				type: "POST",
				dataType: 'script',
				url: $(this).attr("action"),
				data: $(this).serialize() 
			}).done(function() {
				alert($(this).serialize());
			});
			$('#nifty_form')[0].reset();
		});
	});
</script>


<h1>БД</h1>

<a href="/data/myoffers" id="myoffers" class="btn btn-success">Мои заявки</a></br> 
<!-- ------------------- -->
<a href="#nifty_form" id="popup" class="btn btn-success">Добавить нарушение</a>
<div class="hidden">
<form class="nifty_form" id="nifty_form" action="../data/create">
        <p><strong>Добавление нового выявленного нарушения .</strong></p>
        <input type="text" name="offer[obcode]" placeholder="Код объекта"  /><br>
        <input type="text" name="offer[reason]" placeholder="В чем выражается нарушение" required /><br>
        <input type="text" name="offer[adress]" placeholder="Адрес объекта с нарушением" required /><br>
        <input type="text" name="offer[offertype]" placeholder="Вид нарушения" required /><br>
        <input type="text" name="offer[org]" placeholder="Организация, ответственная за нарушение, физическое лицо" required /><br>
        <input type="text" name="offer[offerstat]" placeholder="Примененная статья" required /><br>
        <input type="text" name="offer[kolpredp]" placeholder="Количество предписаний" required /><br>
        <input type="text" name="offer[kolpredupr]" placeholder="Количетсво предупреждений" required /><br>
        <input type="text" name="offer[kolshtraf]" placeholder="Кол-во штрафов" required /><br>
        <input type="text" name="offer[summshtraf]" placeholder="Сумма штрафов" required /><br>

        <button class="button" id="button" type="submit" >Отправить</button>
      </form>
</div>

app/views/data/myoffers.html.erb
	  <div class="table-responsive"> 
	<form class="edit" id="edit" action="../data/edit">
	<table class="table">
		<tr>
			<td>v </td>
			<td> Id нарушения</td>
			<td> Код объекта</td>
			<td>В чем выражается нарушение</td>
			<td>Адрес объекта с нарушением</td>
			<td>Вид нарушения</td>
			<td>Организация</td>
			<td>Примененная статья</td>
			<td>Количество предписаний</td>
			<td>Кол-во штрафов</td>
			<td>Сумма штрафов</td>
		</tr>
		<h1>Список выявленных нарушений</h1>
		<% @BiD.each do |f| %>
		<tr>
			<td><%= radio_button_tag :f,f.id%></td>
			<td><%= f.id %> </td>
			<td><%= f.obcode %></td>
			<td><%= f.reason%></td>
			<td><%= f.adress%></td>
			<td><%= f.offertype%></td>
			<td><%= Organisation.find(f.organisation_id).name%></td>
			<td><%= f.offerstat%></td>
			<td><%= f.kolpredp%></td>
			<td><%= f.kolshtraf%></td>
			<td><%= f.summshtraf%></td>
		</tr>
		<% end %>
	</table>
	    <button class="btn btn-success" id="submit" type="submit">Применить</button>
	</form>
<%= link_to "Назад ",:mains_show %><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
</div>

app/views/data/report.html.erb
<h1>БД</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= link_to "Мои заявки",:profiles_show %><span class="glyphicon glyphicon-user" aria-hidden="true"></span>

</br> 
 <%= link_to "Поиск данных ",:data_search %> <span class="glyphicon glyphicon-search" aria-hidden="true">  </span>
</br>

<%= link_to "Внести данные",:data_add  %><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> </br> 

<%= link_to "Составить отчет по данным" %><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> </br> 

<%=link_to "Просмотр базы пользователей "%> <span class="glyphicon glyphicon-th" aria-hidden="true"></span> </br>
</br>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
 

app/views/data/savechanges.html.erb
<h1>БД</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/lumen/bootstrap.min.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script>

  $(document).ready(function() {

    $("#popup1").magnificPopup();

    $("#form_groupDT").submit(function() {
      $.ajax({
        type: "POST",
        dataType: 'script',
        url: $(this).attr("action"),
        data: $(this).serialize() 
      }).done(function() {
        alert($(this).serialize());
      });
    });
    $("#popup2").magnificPopup();

    $("#form_groupTO").submit(function() {
      $.ajax({
        type: "POST",
        dataType: 'script',
        url: $(this).attr("action"),
        data: $(this).serialize() 
      }).done(function() {
        alert($(this).serialize());
      });
    });

        $("#popup3").magnificPopup();

        $("#form_groupORG").submit(function() {
      $.ajax({
        type: "POST",
        dataType: 'script',
        url: $(this).attr("action"),
        data: $(this).serialize() 
      }).done(function() {
        alert($(this).serialize());
      });
    });

    $(document).ready(function() {
    $("#popup4").magnificPopup();

    $("#form_groupADD").submit(function() {
      $.ajax({
        type: "POST",
        dataType: 'script',
        url: $(this).attr("action"),
        data: $(this).serialize() 
      }).done(function() {
        alert($(this).serialize());
      });
      $('#form-groupADD')[0].reset();
    });
  });
  });
</script>
<body>
<% if user_signed_in?%>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/mains">CourseWork</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><a href="/data/index" id="db">Работа с БД</a></li>
<% if current_user.access == 1 or current_user.access == 0 %>
        <li class="dropdown">
          <a href class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Поиск <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#form_groupDT" id="popup1">По дате</a></li>
            <li><a href="#form_groupTO" id="popup2">По отделу</a></li>
            <li><a href="#form_groupORG" id="popup3">По организациям</a></li>
            <li><a href="#form_groupOF" id="popup4">По типу нарушений</a></li>
          </ul>
        </li>
        <%end%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="/profile/index"><strong>Мой профиль</strong></a></li>
               <% if !user_signed_in? %>
          <li><a href="<%= new_user_session_path %>"><strong>Вход</strong></a></li>
        <% end %>
<!-- <li></li> -->
        <% if user_signed_in? %>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete"><strong>Выход</strong></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
        <%end%>

  <title>Kursovaya</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<%= yield %>

<div class="hidden">

<form class="form-group" id="form_groupDT" action="/search/index">
<h1>Поиск по дате</h1>
  <div class="form-group">
    <label >C:</label>
      <%= select_date Date.today, :prefix => :start_date %> 
  </div>

  <div class="form-group">
    <label>По:</label>
      <%= select_date Date.today, :prefix => :end_date%> 
  </div>
<input type="hidden" name="requesti" value="data">
  <div class="form-group">
        <input type="submit" value="Отправить"></p>
    </div>
  </form>

  <form class="form-group" id="form_groupTO" action="/search/index">
<h1>Поиск по отделам</h1>
  <div class="form-group">
    <label >Выберите отдел:</label>
    <input type="text" name="to" /><br>
  </div>
<input type="hidden" name="requesti" value="otdel">
  <div class="form-group">
        <input type="submit" value="Отправить"></p>
    </div>
  </form>

    <form class="form-group" id="form_groupORG" action="/search/index">
<h1>Поиск по организациям</h1>
  <div class="form-group">
    <label >Выберите организацию:</label>
    <%= select_tag "organisation_id",options_for_select( Organisation.all.map {|c| [c.name, c.id]}) %>
  </div>
<input type="hidden" name="requesti" value="org">
  <div class="form-group">
        <input type="submit" value="Отправить"></p>
    </div>
  </form>

  <form class="form-group" id="form_groupADD" action="../data/create">
        <p><strong>Добавление нового выявленного нарушения .</strong></p>
        <input type="text" name="offer[obcode]" placeholder="Код объекта"  /><br>
        <input type="text" name="offer[reason]" placeholder="В чем выражается нарушение" required /><br>
        <input type="text" name="offer[adress]" placeholder="Адрес объекта с нарушением" required /><br>
        <input type="text" name="offer[offertype]" placeholder="Вид нарушения" required /><br>
        <input class="rfield"type="text" name="offer[org]" placeholder="Организация, ответственная за нарушение, физическое лицо" required /><br>
        <input type="text" name="offer[offerstat]" placeholder="Примененная статья" required /><br>
        <input type="text" name="offer[kolpredp]" placeholder="Количество предписаний" required /><br>
        <input type="text" name="offer[kolpredupr]" placeholder="Количетсво предупреждений" required /><br>
        <input type="text" name="offer[kolshtraf]" placeholdr="Кол-во штрафов" required /><br>
        <input type="text" name="offer[summshtraf]" placeholder="Сумма штрафов" required /><br>
        <input type="file" id="exampleInputFile">

        <button class="button" id="button" onclick="alert('Заявление добавлено')" type="submit" >Отправить</button>
      </form>
  </div>

</body>
</html>

app/views/mains/_form.html.erb
<%= form_for(@main) do |f| %>
  <% if @main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
      <% @main.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mains/edit.html.erb
<h1>Editing main</h1>

<%= render 'form' %>

<%= link_to 'Show', @main %> |
<%= link_to 'Back', mains_path %>

app/views/mains/index.html.erb
<h1>Главное меню</h1>

<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>
</br>

<%= link_to "Мой профиль ",:profile_index,html_options = {:class => "btn btn-link"} %><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
</br> 
 <%= link_to "Работа с базой данных",:data_index,html_options = {:class => "btn btn-link"} %> <span class="glyphicon glyphicon-search" aria-hidden="true">  </span>
</br>
<%=link_to "Просмотр базы пользователей ", :data_show,html_options = {:class => "btn btn-link"}%> <span class="glyphicon glyphicon-th" aria-hidden="true"></span> </br>
</br>

<!-- <div class="panel panel-default">
			<div class="panel-heading">
				<a href=""><%= 'Содержимое новости'%></a>
				<span style="float:left;" class="label label-info"><%= 'User' %></span>
			</div>
			<div class="panel-body">
			<span style="float:left;">
			<%= 'дд.мм.гггг' %>
			</span>
				<span style="font-size: 90%; font-style: italic; float:right;">
				</span>
			</div>
		</div> -->

app/views/mains/new.html.erb
<h1>New main</h1>

<%= render 'form' %>

<%= link_to 'Back', mains_path %>

app/views/otchet/index.html.erb
<h1>Products</h1>

<p>
  Download:
  <%= link_to "CSV", otchet_path(format: "csv") %> |
  <%= link_to "Excel", otchet_path(format: "xls") %>
</p>

<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= offer.id %></td>
    <td><%= offer.id %></td>
    <td><%= offer.id %></td>
  </tr>
<% end %>
</table>

app/views/otchet/index.xls.erb
<table border="1">
    <tr>
      <th> Id нарушения</th>
      <th> Код объекта</th>
      <th>В чем выражается нарушение</th>
      <th>Адрес объекта с нарушением</th>
      <th>Вид нарушения</th>
      <th>Организация</th>
      <th>Примененная статья</th>
      <th>Количество предписаний</th>
      <th>Кол-во штрафов</th>
      <th>Сумма штрафов</th>
    </tr>
    <h1>Список выявленных нарушений</h1>
    <% @offer.each do |f| %>
    <tr>
      <td><%= f.id %> </td>
      <td><%= f.obcode %></td>
      <td><%= f.reason%></td>
      <td><%= f.adress%></td>
      <td><%= f.offertype%></td>
      <td><%= Organisation.find(f.organisation_id).name%></td>
      <td><%= f.offerstat%></td>
      <td><%= f.kolpredp%></td>
      <td><%= f.kolshtraf%></td>
      <td><%= f.summshtraf%></td>
    </tr>
    <% end %>
  </table>

app/views/search/index.html.erb
<form class="form_group" id="data_res">
	<table class="table">
		<tr>
			<td> Id нарушения</td>
			<td> Код объекта</td>
			<td>В чем выражается нарушение</td>
			<td>Адрес объекта с нарушением</td>
			<td>Вид нарушения</td>
			<td>Организация</td>
			<td>Примененная статья</td>
			<td>Количество предписаний</td>
			<td>Кол-во штрафов</td>
			<td>Сумма штрафов</td>
		</tr>
		<h1>Список выявленных нарушений</h1>
		<% @SDB.each do |f| %>
		<tr>
			<td><%= f.id %> </td>
			<td><%= f.obcode %></td>
			<td><%= f.reason%></td>
			<td><%= f.adress%></td>
			<td><%= f.offertype%></td>
			<td><%= f.organisation_id%></td>
			<td><%= f.offerstat%></td>
			<td><%= f.kolpredp%></td>
			<td><%= f.kolshtraf%></td>
			<td><%= f.summshtraf%></td>
		</tr>
		<% end %>
	</table>
	<p>
  Download:
  <%= link_to "Excel", params.merge(:format => :xls) %>

</p>

app/views/search/index.xls.erb
<table border="1">
    <tr>
      <th> Id нарушения</th>
      <th> Код объекта</th>
      <th>В чем выражается нарушение</th>
      <th>Адрес объекта с нарушением</th>
      <th>Вид нарушения</th>
      <th>Организация</th>
      <th>Примененная статья</th>
      <th>Количество предписаний</th>
      <th>Кол-во штрафов</th>
      <th>Сумма штрафов</th>
    </tr>
    <h1>Список выявленных нарушений</h1>
    <% @SDB.each do |f| %>
    <tr>
      <td><%= f.id %> </td>
      <td><%= f.obcode %></td>
      <td><%= f.reason%></td>
      <td><%= f.adress%></td>
      <td><%= f.offertype%></td>
      <td><%= Organisation.find(f.organisation_id).name%></td>
      <td><%= f.offerstat%></td>
      <td><%= f.kolpredp%></td>
      <td><%= f.kolshtraf%></td>
      <td><%= f.summshtraf%></td>
    </tr>
    <% end %>
  </table>